import React from "react";
import Downshift, { resetIdCounter } from "downshift";
import Router from "next/router";
// ApolloConsumer is what allows us to query on demand instead of page load
import { ApolloConsumer } from "react-apollo";
import gql from "graphql-tag";
/* This debounce import will put a limit on the amount of keyup events generated by the user to prevent DDOS or server crash for 
    recieving too many requests in a short amount of time.
*/
import debounce from "lodash.debounce";
import { DropDown, DropDownItem, SearchStyles } from "./styles/DropDown";

const SEARCH_ITEM_QUERY = gql`
	query SEARCH_ITEM_QUERY($searchTerm: String!) {
		items(
			where: {
				OR: [
					{ title_contains: $searchTerm }
					{ description_contains: $searchTerm }
				]
			}
		) {
			id
			image
			title
		}
	}
`;

const routeToItem = (item) => {
	console.log("item: ", item.id);
	Router.push({
		pathname: "/item",
		query: {
			id: item.id,
		},
	});
};

/*
    <Query query={SEARCH_ITEM_QUERY}>
    {(items, {data, loading, error}) => (
        ......
    )}
    </Query>

    IMPORTANT NOTE: 
        normally when you make a query on the client side, you wrap everything you want to return inside of the query tag
        then what happen is the query will fetch the information from the backend on page load. 

        HOWEVER, on something like search options, you want to ONLY run the query when the user is typing something in. 
        To work around this issue, you can use [ApolloConsumer] to query on demand

*/

class AutoComplete extends React.Component {
	state = {
		items: [],
		loading: false,
	};
	onChange = debounce(async (e, client) => {
		console.log("Searching...");
		// turn loading on
		this.setState({ loading: true });
		// Manually query apollo client
		const res = await client.query({
			query: SEARCH_ITEM_QUERY,
			variables: { searchTerm: e.target.value },
		});
		this.setState({
			items: res.data.items,
			loading: false,
		});
	}, 350);

	render() {
		resetIdCounter();
		return (
			<SearchStyles>
				<Downshift
					onChange={routeToItem}
					itemToString={(item) => (item === null ? "" : item.title)}
				>
					{({
						getInputProps,
						getItemProps,
						isOpen,
						inputValue,
						highlightedIndex,
					}) => (
						<div>
							<ApolloConsumer>
								{(client) => (
									<input
										{...getInputProps({
											type: "search",
											placeholder: "Search For An Item",
											id: "search",
											className: this.state.loading ? "loading" : "",
											onChange: (e) => {
												e.persist();
												this.onChange(e, client);
											},
										})}
									/>
								)}
							</ApolloConsumer>
							{isOpen && (
								<DropDown>
									{this.state.items.map((item, index) => (
										<DropDownItem
											{...getItemProps({ item })}
											key={item.id}
											highlighted={index === highlightedIndex}
										>
											<img width="50" src={item.image} alt={item.title} />
											{item.title}
										</DropDownItem>
									))}
									{!this.state.items.length && !this.state.loading && (
										<DropDownItem>Nothing Found for {inputValue}</DropDownItem>
									)}
								</DropDown>
							)}
						</div>
					)}
				</Downshift>
			</SearchStyles>
		);
	}
}

export default AutoComplete;
